services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=PlantRoomDB
      - DB_USER=Nazariy
      - DB_PASSWORD=idM6F-889yASGfh
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=PlantRoomDB
      - POSTGRES_USER=Nazariy
      - POSTGRES_PASSWORD=idM6F-889yASGfh
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "8080:8080"
    depends_on:
      - backend


volumes:
  postgres_data: