# Generated by Django 5.1.6 on 2025-03-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length='1500', null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.PositiveIntegerField(default=0)),
                ('stock_count', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='plants/')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='price_positive'), models.CheckConstraint(condition=models.Q(('discount_percentage__gte', 0), ('discount_percentage__lte', 100)), name='valid_discount_percentage'), models.CheckConstraint(condition=models.Q(('stock_count__gte', 0)), name='valid_stock_count')],
            },
        ),
    ]
