# Generated by Django 5.1.6 on 2025-06-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='plant',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 0), ('rating__lte', 5)), name='inventory_rating_between_0_and_5'),
        ),
    ]
